version: '2'

services:

### PHP-FPM Container #######################################

    proxy:
      build: ./proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./logs/nginx:/var/log/nginx
      links:
        - nginx1
        - nginx2
        - nginx3
        - nginx4

### PHP-FPM Container #######################################

    php-fpm1:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-55
        volumes_from:
            - application1
        expose:
            - "9000"
        links:
            - workspace1

    php-fpm2:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-55
        volumes_from:
            - application2
        expose:
            - "9000"
        links:
            - workspace2

    php-fpm3:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-55
        volumes_from:
            - application3
        expose:
            - "9000"
        links:
            - workspace3

    php-fpm4:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-55
        volumes_from:
            - application4
        expose:
            - "9000"

### Laravel Application Code Container ######################

    application1:
        build: ./application
        volumes:
            - ../branch1:/var/www/laravel

    application2:
        build: ./application
        volumes:
            - ../branch2:/var/www/laravel

    application3:
        build: ./application
        volumes:
            - ../branch3:/var/www/laravel

    application4:
        build: ./application
        volumes:
            - ../branch4:/var/www/laravel

### Databases Data Container ################################

    data:
        build: ./data
        volumes:
            - /var/lib/mysql
            - /var/lib/postgres
            - /var/lib/mariadb
            - /var/lib/redis
            - /var/lib/memcached
            - /var/lib/neo4j/data

### Nginx Server Container ##################################

    nginx1:
        build: 
            context: ./nginx
            args: 
                PHP_UPSTREAM: php-fpm1
        volumes_from:
            - application1
        volumes:
            - ./logs/nginx/:/var/log/nginx
        expose:
            - "80"
        links:
            - php-fpm1

    nginx2:
        build:
            context: ./nginx
            args:
                PHP_UPSTREAM: php-fpm2
        volumes_from:
            - application2
        volumes:
            - ./logs/nginx/:/var/log/nginx
        expose:
            - "80"
        links:
            - php-fpm2

    nginx3:
        build:
            context: ./nginx
            args:
                PHP_UPSTREAM: php-fpm3
        volumes_from:
            - application3
        volumes:
            - ./logs/nginx/:/var/log/nginx
        expose:
            - "80"
        links:
            - php-fpm3

    nginx4:
        build:
            context: ./nginx
            args:
                PHP_UPSTREAM: php-fpm4
        volumes_from:
            - application4
        volumes:
            - ./logs/nginx/:/var/log/nginx
        expose:
            - "80"
        links:
            - php-fpm4

### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dashboard
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes_from:
            - data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret

### MariaDB Container #######################################

    mariadb:  
        build: ./mariadb
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Neo4j Container #########################################

    neo4j:
        build: ./neo4j
        ports:
            - "7474:7474"
            - "1337:1337"
        environment:
            - NEO4J_AUTH=homestead:secret
        volumes_from:
            - data

### Redis Container #########################################

    redis:
        build: ./redis
        volumes_from:
            - data
        ports:
            - "6379:6379"

### Memcached Container #####################################

    memcached:
        build: ./memcached
        volumes_from:
            - data
        ports:
            - "11211:11211"
        links:
            - php-fpm1

### Beanstalkd Container ####################################

    beanstalkd:
        build: ./beanstalkd
        ports:
            - "11300:11300"
        privileged: true
        links:
            - php-fpm1

### Beanstalkd Console Container ############################

    beanstalkd-console:
        build: ./beanstalkd-console
        ports:
            - "2080:2080"
        links:
            - beanstalkd

### Workspace Utilities Container ###########################

    workspace1:
        build: ./workspace
        volumes_from:
            - application1
        tty: true

    workspace2:
        build: ./workspace
        volumes_from:
            - application2
        tty: true

    workspace3:
        build: ./workspace
        volumes_from:
            - application3
        tty: true

### Add more Containers below ###############################
