# PHP + NGINX Container #----------------------------------
nginx-proxy:
  image: nginx
  container_name: nginx-proxy
  ports:
    - "80:80"
  volumes:
    - nginx-proxy.conf:/etc/nginx/nginx.conf
    - ./logs/nginx:/var/log/nginx
  
php-nginx1:
  image: laradock/php56nginx:0.1.0
  container_name: php-nginx-1
  ports:
    - "8080:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - /www/branches/branch1:/var/www
    - ./logs/nginx:/var/log/nginx
  links:
    - mysql
#    - redis
  privileged: true

php-nginx2:
  image: laradock/php56nginx:0.1.0
  container_name: php-nginx-2
  ports:
    - "8081:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - /www/branches/branch2:/var/www
    - ./logs/nginx:/var/log/nginx
  links:
    - mysql
#    - redis
  privileged: true

php-nginx3:
  image: laradock/php56nginx:0.1.0
  container_name: php-nginx-3
  ports:
    - "8082:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - /www/branches/branch3:/var/www
    - ./logs/nginx:/var/log/nginx
  links:
    - mysql
#    - redis
  privileged: true

# MySQL Container #----------------------------------------
mysql:
  image: laradock/mysql:0.1.0
  container_name: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - data
  environment:
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  privileged: true

# Redis Container #----------------------------------------
#redis:
#  image: laradock/redis:0.1.0
#  container_name: redis
#  ports:
#    - "6379:6379"
#  volumes_from:
#    - data
#  volumes:
#    - ./logs/redis:/var/log/redis
#  privileged: true

# Data Volume Container #----------------------------------
data:
  image: laradock/data:0.1.0
  container_name: data
  volumes:
    - /var/lib/mysql
    - /var/lib/redis

# Beanstalkd Container #-----------------------------------
# beanstalkd:
#   image: laradock/beanstalkd:0.1.0
#   container_name: beanstalkd
#   ports:
#     - "11300:11300"
#   privileged: true

#----------------------------------------------------------
